### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by rl421403** [LevPasha/instabot.py#18]
I ran this program and got this error.

    root:~/insta# python3 instabot.py
    Traceback (most recent call last):
      File "instabot.py", line 337, in <module>
        log_mod = 1)
      File "instabot.py", line 91, in __init__
        self.write_log(log_string)
      File "instabot.py", line 320, in write_log
        self.hdrl = logging.FileHandler(self.log_full_path, mode='w')
      File "/usr/lib/python3.4/logging/__init__.py", line 992, in __init__
        StreamHandler.__init__(self, self._open())
      File "/usr/lib/python3.4/logging/__init__.py", line 1016, in _open
        return open(self.baseFilename, self.mode, encoding=self.encoding)
    FileNotFoundError: [Errno 2] No such file or directory: '/var/www/python/log/user_04.03.2016_12:20.log'

**Comment by LevPasha** [comment]
Hi! Look like you try log to file. If you don't need it - 
```python
bot = InstaBot(......, log_mod = 0)
```
this will log to console.

**Comment by rl421403** [comment]
Now, I did that and it did not give any error. But what exactly it is doing?
This is the output I got. And it keeps going every second, so I abort the process.

    root:~/insta# python3 instabot.py
    Insta Bot v0.05 start at 05.03.2016 05:15:
    Try to login by myiguser...
    Look like login by myiguser succes!
    Get media id by tag: tag1
    Get media id by tag: tag2
    Get media id by tag: tag3
    Get media id by tag: tag2
    Get media id by tag: tag2
    Get media id by tag: tag2
    Get media id by tag: tag1
    Get media id by tag: tag2
    Get media id by tag: tag2
    Get media id by tag: tag3
    Get media id by tag: tag1
    Get media id by tag: tag1
    Get media id by tag: tag3
    Get media id by tag: tag2
    Get media id by tag: tag3
    Get media id by tag: tag2

This is my bit code, if it helps.

    bot = InstaBot('myiguser', 'mypassword',
                   like_per_day=300,
                   media_max_like=50,
                   media_min_like=5,
                   tag_list = ['tag1', 'tag2', 'tag3'],
                   max_like_for_one_tag=100,
                   log_mod = 0)
    bot.auto_mod()

What exactly it is doing every second? If it is following or liking a image every second then would it not be good to add a delay?

**Comment by LevPasha** [comment]
@rl421403 hi. Bot try to get some media by tags `['tag1', 'tag2', 'tag3']`. If it get some media - it will start to like it with some delay. In your example - there is now any media by tag `['tag1', 'tag2', 'tag3']`. You should change tag for something normal like `['cat', 'girl', 'car']`.

**Comment by rl421403** [comment]
I was doing that `['cat', 'girl', 'car']`.

How much is the delay?

**Comment by LevPasha** [comment]
@rl421403 See reedme: delay (in second) = (24 hour * 60 minute * 60 second / like_per_day). Change like_per_day (more value - less delay) to change delay.

**Comment by rl421403** [comment]
I think I am starting to understanding how this bot is working.
BTW what is this `follow_time=5*60*60` in `example.pl`

**Comment by LevPasha** [comment]
@rl421403 this parameter mean how many time bot follow user. If user have followed by bot, it will unfollow (if setting) from `follow_time` seconds.

I will write it all in readme, when have time!

**Comment by Zinartcode** [comment]
File "C:/Users/Artur/PycharmProjects/untitled1/InstaWeb.py", line 92
    self.time_in_day = 24*60*60
    ^
IndentationError: unexpected indent

Process finished with exit code 1


Also all comands with "self" marked as an error, and when i try to install package for "self" it says install is failed. Can someone explain me why please

**Comment by rl421403** [comment]
@LevPasha can you show me example codes for simple follow and unfollow.

1. I just want this bot to follow 60 users (with a delay of 1 min) and then stop. No like or anything else.

2. Then I want another bot to unfollow 60 users (with a delay of 1 min) and then stop.

I will be triggering these commands at specific time of day with cron. So I don't want it to keep running.

**Comment by LevPasha** [comment]
@rl421403 try something like this. First you create class with par you need, second you set your `time_in_day` to 60 minute (that mean bot will make all comand in 60 minute, not at 24 hour as default). Than you start bot `bot.new_auto_mod()`. Also you should set `follow_time` - how many time you need follow user. Bot follow user, than wait `follow_time`, than unfollow this user.

```python
bot = InstaBot(login="your_login", password="your_password",
               like_per_day=0,
               max_like_for_one_tag=0,
               follow_per_day=60,
               follow_time= "SET YOUR FOLLOW TIME",
               unfollow_per_day=60,
               comments_per_day=0,
               log_mod=0)

bot.time_in_day = 60*60
bot.new_auto_mod()
```

BUT! When 60*60 time end, bot don't stop to follow new users. If you need to stop - you shold write some cod to stop it youself.
