### ISSUE TITLE
Getting error when login

### ISSUE THREAD

**Issue by ahansson89** [LevPasha/instabot.py#188]
I am getting the following output. When using the example.py with my username and password:

```
Instabot v1.0.1 started at 13.09.2016 19:46:

Trying to login as example...

Traceback (most recent call last):
  File "/var/instabot/example.py", line 16, in <module>
    log_mod=0)
  File "/var/instabot/instabot.py", line 151, in __init__
    self.login()
  File "/var/instabot/instabot.py", line 174, in login
    r = self.s.get(self.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(101, 'Network is unreachable'))

```

**Comment by ahansson89** [comment]
I restarted my computer and it is now working as expected!
