### ISSUE TITLE
Crashes...

### ISSUE THREAD

**Issue by bobduckling221** [LevPasha/instabot.py#203]
Basically i launch it it, it logs in,, and then cmd just crashes and completely turns off. The bot turns off before it even gets to like or follow. Please help.

**Comment by virginsince1997** [comment]
Try running it with python IDE and sees what happens, make sure if you have
python 27 and 35 on the same machine, they aren't conflicting

**Comment by bobduckling221** [comment]
`Instabot v1.0.1 started at 02.10.2016 18:22:

Trying to login as mr_soundaniel...

mr_soundaniel login success!
Blacklisted user ______ added with ID: 11341294
Traceback (most recent call last):
  File "C:\Users\_____\Desktop\instabot.py-master\example.py", line 18, in <module>
    log_mod=0)
  File "C:\Users\_____\Desktop\instabot.py-master\instabot.py", line 157, in __init__
    self.populate_user_blacklist()
  File "C:\Users\_______\Desktop\instabot.py-master\instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']
IndexError: list index out of range
>>> 
`

this is basically what it shows.... any ideas?

**Comment by bobduckling221** [comment]
`Instabot v1.0.1 started at 02.10.2016 18:22:

Trying to login as ______l...

_____ login success!
Blacklisted user _____ added with ID: 11341294
Traceback (most recent call last):
  File "C:\Users\_____\Desktop\instabot.py-master\example.py", line 18, in <module>
    log_mod=0)
  File "C:\Users\_____\Desktop\instabot.py-master\instabot.py", line 157, in __init__
    self.populate_user_blacklist()
  File "C:\Users\_____\Desktop\instabot.py-master\instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']
IndexError: list index out of range
>>> 
`

This is what it shows. Any ideas?

**Comment by hfmhull** [comment]
I had this issue as well but it was just with the "example" names of hellokitty and what not so I just deleted them and resaved it in idle and it worked great.
