### ISSUE TITLE
Error after launching

### ISSUE THREAD

**Issue by Rolaman** [LevPasha/instabot.py#204]
I use IDE Anaconda for python 3.5
When I've started, there're errors and I have no idea what I have to do
Help please if you can

Here's a log:

runfile('D:/My_Code/instabot.py-master/example.py', wdir='D:/My_Code/instabot.py-master')
Reloaded modules: userinfo, instabot
Instabot v1.0.1 started at 03.10.2016 22:06:

Trying to login as whereroman...

whereroman login success!
Blacklisted user hellokitty added with ID: 11341294
Traceback (most recent call last):

  File "<ipython-input-12-c6e4616b1fde>", line 1, in <module>
    runfile('D:/My_Code/instabot.py-master/example.py', wdir='D:/My_Code/instabot.py-master')

  File "D:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "D:/My_Code/instabot.py-master/example.py", line 18, in <module>
    log_mod=0)

  File "D:\My_Code\instabot.py-master\instabot.py", line 157, in __init__
    self.populate_user_blacklist()

  File "D:\My_Code\instabot.py-master\instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']

IndexError: list index out of range

**Comment by drewhga** [comment]
These might help.
1. This bot was coded in python 2.7 so its no surprise you get the errors
in the first part of the traceback so I suggest you use python 2.7

2. The second part of the error stems from the latest merge so you should
check out earlier threads on that, there are a few answers which can help
you out.

**Comment by Rolaman** [comment]
Thank you)
I'll try to use python 2.7

**Comment by polaroi8d** [comment]
@Rolaman if the problem solved, please closed the issue.
