### ISSUE TITLE
Getting "NameError: global name 's' is not defined" when entering proxy

### ISSUE THREAD

**Issue by alexcheninfo** [LevPasha/instabot.py#208]
I'm using `example.py` plus a proxy (Python 2.7 on Ubuntu 15.10):

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from instabot import InstaBot

bot = InstaBot(login="user", password="password",
               like_per_day=1000,
               comments_per_day=0,
               tag_list=['rottweiler', 'rottweilers'],
               max_like_for_one_tag=50,
               follow_per_day=300,
               follow_time=5*60*60,
               unfollow_per_day=150,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               proxy="user:password@204.77.12.44:21251")

bot.new_auto_mod()
```

However, I get this error:

```
Traceback (most recent call last):
  File "example.py", line 19, in <module>
    proxy='user:password@204.77.12.44:21251')
  File "/home/alex/instabots/rottweiler/instabot.py", line 145, in __init__
    s.proxies.update(proxies)
NameError: global name 's' is not defined
```

Is this a bug? Or there's something wrong with my proxy?

(The bot runs okay without the proxy. And I'm using the latest version of Instabot. Also, I already did `pip install requests`)

**Comment by polaroi8d** [comment]
@Mike97M wrote the proxy feature. Can you help to @alexcheninfo ?

**Comment by Mike97M** [comment]
Replace: `s.proxies.update(proxies)` with `self.s.proxies.update(proxies)`

**Comment by polaroi8d** [comment]
Thanks @Mike97M for the short time answer. @alexcheninfo if its okey, please closed the issue.

**Comment by alexcheninfo** [comment]
Thanks for the fast reply. Now I get a smaller error ...

```
Login error! Connection error!
Completed populating user blacklist with IDs
```

**Comment by alexcheninfo** [comment]
@Mike97M @polaroi8d Thanks for the fast reply. It worked!
