### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ilkerp** [LevPasha/instabot.py#224]
Hello There,

When i try to run modified example.py i got this error:

```
Trying to login as johndoe...

johndoe login success!
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    log_mod=0)
  File "/root/instabot.py/instabot.py", line 157, in __init__
    self.populate_user_blacklist()
  File "/root/instabot.py/instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']
IndexError: list index out of range
```
i have Python 2.7.6 

any idea ?

**Comment by ilkerp** [comment]
I've resolved the problem. :)
```

    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={'hellokitty':'', 'hellokitty3':''},
```

these two rows caused to problem. when i deleted it is working fine.
