### ISSUE TITLE
After Login Error

### ISSUE THREAD

**Issue by epicbrony** [LevPasha/instabot.py#226]
I login in, it said success and then crashes? Help?

**Comment by virginsince1997** [comment]
Try using python IDLE to run it

**Comment by epicbrony** [comment]
@virginsince1997 Im new to python :/

**Comment by epicbrony** [comment]
Traceback (most recent call last):
  File "C:\Users\theep\AppData\Local\Programs\Python\Python35-32\instabot.py-master\example.py", line 18, in <module>
    log_mod=0)
  File "C:\Users\theep\AppData\Local\Programs\Python\Python35-32\instabot.py-master\instabot.py", line 157, in __init__
    self.populate_user_blacklist()
  File "C:\Users\theep\AppData\Local\Programs\Python\Python35-32\instabot.py-master\instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']
IndexError: list index out of range

**Comment by virginsince1997** [comment]
In Windows search bar,  type python, ud see IDLE(PYTHON GUI)... IN PYTHON
GUI, CLICK OPEN, LOCATE THE SCRIPT, INSTABOT,,, OPEN, CLICK RUN>>>RUN MODULE

**Comment by kemong** [comment]
hy @epicbrony check boc's answer
"bobduckling221 commented a day ago
 delete [0] in line 167
 and then delete self.populate_user_blacklist() in line 157"

cheers :beers:

**Comment by virginsince1997** [comment]
Be sure to input your details, password and username

**Comment by epicbrony** [comment]
I got it, I deleted the Blacklist Users Lol, Thanks
