### ISSUE TITLE
HI guys i Have big problem please help!!!

### ISSUE THREAD

**Issue by nathanvvv** [LevPasha/instabot.py#233]
This is what pops up when i try to run. Please help i am completely new to python.

`Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
===== RESTART: C:\Users\nathanvnv\Desktop\instabot.py-master\example.py =====
Instabot v1.0.1 started at 16.10.2016 19:09:

Trying to login as +++++++...

Traceback (most recent call last):
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\connection.py", line 98, in create_connection
    raise err
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\connection.py", line 88, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
    conn = self._new_conn()
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038ABE50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038ABE50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nathanvnv\Desktop\instabot.py-master\example.py", line 31, in <module>
    '.id','_id','bags'])
  File "C:\Users\nathanvnv\Desktop\instabot.py-master\instabot.py", line 184, in __init__
    self.login()
  File "C:\Users\nathanvnv\Desktop\instabot.py-master\instabot.py", line 223, in login
    r = self.s.get(self.url)
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nathanvnv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038ABE50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
>>> 
`

**Comment by virginsince1997** [comment]
*Try reinstalling Urlib3*
Type
"pip install urllib3" without quotes in cmd.
Make sure you type "python" first in Cmd.

*Try This First*
If you get category already satisfied
Remove Urlib3 with
"pip remove urllib".

I suggest you install, type

"pip install 'requests[security]'" in cmd.

**Comment by virginsince1997** [comment]
Use python 2.7 for this script am not sure 3 works.

**Comment by nathanvvv** [comment]
SyntaxError: invalid syntax
>>> pip install urllib3
  File "<stdin>", line 1
    pip install urllib3
              ^
SyntaxError: invalid syntax
>>>

I try but not work. @virginsince1997 
I use python 3

**Comment by drewhga** [comment]
You should use python 2.7, python 3.x will definitely give you problems

**Comment by virginsince1997** [comment]
Try using Python 2.7, unistall 3

**Comment by LevPasha** [comment]
Try last version. I test it on python 3+.
