### ISSUE TITLE
'Set' object...?

### ISSUE THREAD

**Issue by saveasex** [LevPasha/instabot.py#257]
Traceback (most recent call last):
  File "C:\Program Files\instabot.py-master\example.py", line 27, in <module>
    proxy='',)
  File "C:\Program Files\instabot.py-master\src\instabot.py", line 185, in __init__
    self.populate_user_blacklist()
  File "C:\Program Files\instabot.py-master\src\instabot.py", line 197, in populate_user_blacklist
    self.user_blacklist[user]=id_user
TypeError: 'set' object does not support item assignment

**Comment by polaroi8d** [comment]
#245
