### ISSUE TITLE
Problem!!!

### ISSUE THREAD

**Issue by nathanvvv** [LevPasha/instabot.py#279]
After 35 likes it turns off! plz help

`Traceback (most recent call last):
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nathan\Desktop\instabot.py-master\example.py", line 55, in <module>
    bot.new_auto_mod()
  File "C:\Users\nathan\Desktop\instabot.py-master\src\instabot.py", line 519, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\nathan\Desktop\instabot.py-master\src\instabot.py", line 572, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\Users\nathan\Desktop\instabot.py-master\src\instabot.py", line 597, in check_exisiting_comment
    check_comment = self.s.get(url_check)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nathan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
>>> 
`

**Comment by wrackful** [comment]
please send code file example.py

**Comment by nathanvvv** [comment]
@wrackful can't send python file.. here is code



#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys, os
sys.path.append(os.path.join(sys.path[0],'src'))

from instabot import InstaBot
from check_status import check_status
from feed_scanner import feed_scanner
from unfollow_protocol import unfollow_protocol
from follow_protocol import follow_protocol
import time


bot = InstaBot(login="", password="",
               like_per_day=1000,
               comments_per_day=150,
               tag_list=['инстаграмнедели','thestreetnetwork', 'following,''tagsforlike,''tagsforfollow','vsconature', 'vscophile', 'vscogood', 'vscogrid', 'vscogallery', 'vscoedit', 'vscoonly', 'vscomoment', 'vscotop' ,'vscoexpo', 'vscoeurope', 'under3kyo', 'взаимныелайки', 'взаимнаяподписка', 'играшоут','играшаут','пиаригра'],
               tag_blacklist=['rain', 'thunderstorm'],
               user_blacklist={},
               max_like_for_one_tag=46,
               follow_per_day=0,
               follow_time=1*60,
               unfollow_per_day=800,
               unfollow_break_min=20,
               unfollow_break_max=30,
               log_mod=0,
               proxy='',
               # Use unwanted username list to block users which have username contains one of this string
               ## Doesn't have to match entirely example: mozart will be blocked because it contains *art
               ### freefollowers will be blocked because it contains free
               unwanted_username_list=['free'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW PEOPLE WHO DON'T FOLLOW BACK BASED ON RECENT FEED ONLY")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW PEOPLE BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
           ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0 :
        bot.new_auto_mod()

    elif mode == 1 :
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10*60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) <50 :
                feed_scanner(bot)
                time.sleep(5*60)
                follow_protocol(bot)
                time.sleep(10*60)
                check_status(bot)

    elif mode == 2 :
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3 :
        unfollow_protocol(bot)
        time.sleep(10*60)

    elif mode == 4 :
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10*60)

    elif mode == 5 :
        bot.bot_mode=2
        unfollow_protocol(bot)

    else :
        print ("Wrong mode!")

**Comment by blacksector** [comment]
It is working normally on my end without any issues. It seems Instagram is constantly closing the connection. A few questions, on your computer are you logged into any other instagram accounts via instagram.com on your browser? Maybe that is affecting it? Just a guess. You might want to also re-download the instabot.py code if you haven't already, maybe you didn't get an update?

**Comment by blacksector** [comment]
Please try one other thing, make 'comments_per_day=0' instead of the value of 150. Maybe that is another factor.

**Comment by wrackful** [comment]
this code worked for me and no problem...,
please check for update python..check internet connection,check proxy...
my instabot and another files has upgrade...with edited by my self
i do login to many account with any terminal or shell...and no problem for this...
limits instagram only for actions(like,unlike,follow,unfollow,change profile picture and others...) and this is a different for any user ... (old user,new user,high activity,low activity)
this bot had few problems but it is be solved
you can edit some files ,Tailored to the needs
for example i needed a module for like a post last specific user...

**Comment by nathanvvv** [comment]
@wrackful @blacksector yes i set comments to 0 and it worked... But why? Shouldn't it work with comments?

**Comment by blacksector** [comment]
@nathanvvv Unfortunately I have not tested commenting as of yet. It may depend on the Python version? Change your python version from 2.7 to 3.x or vice versa, the library is still under heavy development so this could be one reason why it is not working as the commenting part of the API is probably not working. I'll test commenting and get back to you.

**Comment by nathanvvv** [comment]
No I'm not blocked.... I'm pretty sure. I'll try to switch to 2.7. But so far i can survive on likes and follows/unfollows))) @blacksector

**Comment by blacksector** [comment]
@nathanvvv sounds good. Comments are working for me though.

**Comment by trohit920** [comment]
Hi,
I am also getting similar error. Can you please take a look?

Traceback (most recent call last):
  File "C:/Users/rohit/Desktop/Python/keras_classification.py", line 21, in <module>
    model = applications.VGG16(weights = 'imagenet', include_top = False)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\applications\vgg16.py", line 169, in VGG16
    cache_subdir='models')
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 220, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 277, in urlretrieve
    block = fp.read(bs)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Here is the code-

from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dropout, Flatten, Dense

# path to the model weights files.
weights_path = '../keras/examples/vgg16_weights.h5'
top_model_weights_path = 'fc_model.h5'
# dimensions of our images.
img_width, img_height = 150, 150

train_data_dir = 'cats_and_dogs_small/train'
validation_data_dir = 'cats_and_dogs_small/validation'
nb_train_samples = 2000
nb_validation_samples = 800
epochs = 50
batch_size = 16

# build the VGG16 network
model = applications.VGG16(weights='imagenet', include_top=False)
print('Model loaded.')

# build a classifier model to put on top of the convolutional model
top_model = Sequential()
top_model.add(Flatten(input_shape=model.output_shape[1:]))
top_model.add(Dense(256, activation='relu'))
top_model.add(Dropout(0.5))
top_model.add(Dense(1, activation='sigmoid'))

# note that it is necessary to start with a fully-trained
# classifier, including the top classifier,
# in order to successfully do fine-tuning
top_model.load_weights(top_model_weights_path)

# add the model on top of the convolutional base
model.add(top_model)

# set the first 25 layers (up to the last conv block)
# to non-trainable (weights will not be updated)
for layer in model.layers[:25]:
    layer.trainable = False

# compile the model with a SGD/momentum optimizer
# and a very slow learning rate.
model.compile(loss='binary_crossentropy',
              optimizer=optimizers.SGD(lr=1e-4, momentum=0.9),
              metrics=['accuracy'])

# prepare data augmentation configuration
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1. / 255)

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='binary')

validation_generator = test_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='binary')

# fine-tune the model
model.fit_generator(
    train_generator,
    samples_per_epoch=nb_train_samples,
    epochs=epochs,
    validation_data=validation_generator,
    nb_val_samples=nb_validation_samples)
