### ISSUE TITLE
help

### ISSUE THREAD

**Issue by aipmy** [LevPasha/instabot.py#311]
C:\Users\aipmy\Downloads\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from instabot import InstaBot
  File "C:\Users\aipmy\Downloads\instabot.py-master\src\instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "C:\Users\aipmy\Downloads\instabot.py-master\src\userinfo.py", line 4, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by polaroi8d** [comment]
Please, ask questions here #245
