### ISSUE TITLE
ui.get_followers not working

### ISSUE THREAD

**Issue by drallcom3** [LevPasha/instabot.py#350]
```
ui = UserInfo()
bot = InstaBot( the usual )

ui.search_user(user_id="50417061")
print(ui.user_name)
print(ui.user_id)
ui.get_followers(limit=5)
print(ui.followers)
```

Crashes at get_followers:
```
Traceback (most recent call last):
  File "instabot.py-master\main2.py", line 48, in <module>
    ui.get_followers(limit=5)
  File "instabot.py-master\src\userinfo.py", line 90, in get_followers
    r = json.loads(followers.text)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ohld** [comment]
Have the same issue

**Comment by ohld** [comment]
Found in the main page if this repository, that this methods don't work after "June 1 2016"

**Comment by gilllambrigts** [comment]
This is not possible anymore. You used to be able to see all the followers when you pulled the JSON of a page, sadly Instagram now only returns the amount of followers, rather than all their links.

Gill

**Comment by ohld** [comment]
@gilllambrigts It is possible if you scrap the page of web version. You can press in "followers" section and scroll down until the end. Yes, it is not so easy to implement but possible

**Comment by drallcom3** [comment]
So not possible anymore, sadly. Still a great bot!

**Comment by nkwsy** [comment]
Any way to get just follower count?

**Comment by drallcom3** [comment]
@ohld it's working with the python API. Returns you the latest followers of someone as a list. No idea why it's not updated in this bot. Seems pretty trivial for someone good in Python (I'm not).
