### ISSUE TITLE
NEED HELP!!!

### ISSUE THREAD

**Issue by justinklme** [LevPasha/instabot.py#376]
Traceback (most recent call last):
  File "/Users/Sandy/Downloads/instabot.py-master/example Kopie.txt", line 6, in <module>
    from instabot import InstaBot
  File "/Users/Sandy/Downloads/instabot.py-master/src/instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "/Users/Sandy/Downloads/instabot.py-master/src/userinfo.py", line 4, in <module>
    import requests
ImportError: No module named requests

What can I do?

**Comment by ekremgurdal** [comment]
"Requests" library is not installed in your interpreter. You should install this package. If you are using linux, command -> pip install requests 
If you are using windows, you can install this package with your ide
