### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by Plushkin** [LevPasha/instabot.py#381]
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> 
====== RESTART: /Users/Plushkin/Downloads/instabot.py-master/example.py ======
Instabot v1.1.0 started at 14.02.2017 13:54:
Checking user info..
Follower : 693
Following : 526
Media : 244
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are following this account
sivi_olya
Unfollow: 2019056047 #1.
Trying to like media: 1449967699442954636
Liked: 1449967699442954636. Like #2.
Trying to like media: 1449967596992227880
Liked: 1449967596992227880. Like #3.
Traceback (most recent call last):
  File "/Users/Plushkin/Downloads/instabot.py-master/example.py", line 60, in <module>
    bot.new_auto_mod()
  File "/Users/Plushkin/Downloads/instabot.py-master/src/instabot.py", line 525, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/Plushkin/Downloads/instabot.py-master/src/instabot.py", line 578, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/Users/Plushkin/Downloads/instabot.py-master/src/instabot.py", line 614, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by michaelew** [comment]
I was having a similar issue, I worked around it by commenting out line 578 in src/instabot.py and modifying line 577 to `and len(self.media_by_tag) > 0:`.

**Comment by Plushkin** [comment]
I correctly changed?
 ```
  def new_auto_mod_comments(self):
        if time.time() > self.next_iteration["Comments"] and self.comments_per_day != 0 \
                and len(self.media_by_tag) > 0:
##                and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
            comment_text = self.generate_comment()
            log_string = "Trying to comment: %s" % (self.media_by_tag[0]['id'])
            self.write_log(log_string)
            if self.comment(self.media_by_tag[0]['id'], comment_text) != False:
                self.next_iteration["Comments"] = time.time() + \
                                                  self.add_time(self.comments_delay)
```

**Comment by Plushkin** [comment]
i try this changes, but this not work at all((((
