### ISSUE TITLE
Bot logout after error - ValueError No JSON object could be decoded

### ISSUE THREAD

**Issue by Sadarex** [LevPasha/instabot.py#407]
Hi :)
I hope someone can help me with this.

I'm using this bot for some days now and have the problem that it crashes everytime after some hours. 

The error message:
```
Traceback (most recent call last):
  File "./sadarex.py", line 79, in <module>
    bot.new_auto_mod()
  File "/home/instagrambot/bot-sadarex/instabot.py/src/instabot.py", line 529, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/instagrambot/bot-sadarex/instabot.py/src/instabot.py", line 582, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/instagrambot/bot-sadarex/instabot.py/src/instabot.py", line 610, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ValueError: No JSON object could be decoded
```

Logs from the last two times attached. (shortened)
[log1.txt](https://github.com/LevPasha/instabot.py/files/821508/log1.txt)
[log2.txt](https://github.com/LevPasha/instabot.py/files/821507/log2.txt)

At first it's working fine, but after some time it stops to like/comment, starts to unfollow and when the bot reaches half of the unfollow counter (Unfollow: 1501536902 #16 of 32.) there is a logout.

Any ideas? I have no coding experience with python :\

best regards
Sadarex

**Comment by LevPasha** [comment]
Try to use python 3+

**Comment by fireuniversal** [comment]
Solution is at #438 .Leave a like & comment after it fixes the problem. Enjoy 👍
