### ISSUE TITLE
Cant start example.py

### ISSUE THREAD

**Issue by svallej** [LevPasha/instabot.py#49]
Hi im having this issue when i try to run: _python3 example.py_
```
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    log_mod=0)
  File "/Users/vallejo/Downloads/instabot.py-master/instabot.py", line 119, in __init__
    self.s = requests.Session()
AttributeError: 'module' object has no attribute 'Session'
```

Any one know how to resolve

**Comment by amk11** [comment]
Run it using Python 2.7 as this script does not work with python 3
